# Configuration file
# key = value
quarkus.smallrye-health.root-path=/health
quarkus.smallrye-health.liveness-path=liveness
quarkus.smallrye-health.readiness-path=readiness
quarkus.http.read-timeout=300s
quarkus.http.body.max-body-size=32M
